### ISSUE TITLE
move composeFireRaster() to package to enable re-use

### ISSUE THREAD

**Issue by achubaty** [tati-micheletti/caribouPopGrowthModel#2]
1. Where to put this? `fireSenseUtils` for now, although it's more general. `LandR`?
2. Ensure it's backwards compatible with e.g. this module

**Comment by achubaty** [comment]
@tati-micheletti `composeFireRaster()` here is very similar to `updateFireLayer()` (not on GitHub?).
Reviewing the info you sent me, I think `updateFireLayer()` is the verison to use with fireSense enhancements we dicussed -- but can we chat about whether that function should replace this here?

**Comment by tati-micheletti** [comment]
Yes, you can use that one, but please don't replace it here. I'll do it
later on. I need this module to stay put until we finish delivering the
predictions. Thanks.

**Comment by achubaty** [comment]
after going through this, it's not going to be re-usable.

updating fire layers during simulation is a _much_ simpler task, and this function is doing a bunch of additional things, and creating many more objects / files than needed.

**Comment by tati-micheletti** [comment]
This module is stand alone as is. It will be adapted to historical fire
layers coming from simulation. Additional things and objects being created
are necessary for posthoc diagnosis and plots.
