### ISSUE TITLE
update module metadata to include caribouMetrics package

### ISSUE THREAD

**Issue by achubaty** [tati-micheletti/caribouPopGrowthModel#3]
which version of the package is actually used/working?

- `tati-micheletti/caribouMetrics@dde5823d097f8362f279d7bdc5f4bf597799a898`? (not working?)
- `LandSciTech/caribouMetrics`?

**Comment by tati-micheletti** [comment]
LandSciTech/caribouMetrics

There were some modifications to the package, and I adapted my module code to be compatible with it.

**Comment by tati-micheletti** [comment]
Updated
